# render.yaml
services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    # No startCommand here!
    plan: free  # or starter, depending on your preference
    regions:
      - iad  # choose your region (e.g., iad = Washington, D.C.)
    autoDeploy: true
