services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-mysql-host.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: ecommerce_portal
      - key: DB_USERNAME
        value: yourusername
      - key: DB_PASSWORD
        sync: false # Set manually in Render dashboard for security
