services:
  - type: web
    name: NakarmiMartX
    runtime: docker
    plan: free
    repo: https://github.com/qubinakarmi/NakarmiMartX
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
